# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "55 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics-base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: base
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics/base.svg
          user: futuretech6
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
          repositories_forks: no

          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: jupyter notebook, html, tsql, css, scss
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_traffic: yes

  github-metrics-wakatime:
    runs-on: ubuntu-latest
    steps:
      - name: wakatime
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/wakatime.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: futuretech6

  github-metrics-leetcode:
    runs-on: ubuntu-latest
    steps:
      - name: leetcode
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/leetcode.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: futuretech6c

  github-metrics-16personalities:
    runs-on: ubuntu-latest
    steps:
      - name: 16personalities
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/16personalities.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_16personalities: yes
          plugin_16personalities_scores: yes
          plugin_16personalities_sections: personality, profile, traits
          plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}

  github-metrics-steam:
    runs-on: ubuntu-latest
    steps:
      - name: steam
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/steam.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_steam: yes
          plugin_steam_achievements_limit: 2
          plugin_steam_games_limit: 5
          plugin_steam_playtime_threshold: 0 # most play games require playtime > threshold
          # plugin_steam_recent_games_limit: 2
          plugin_steam_games_ignored: 431960
          plugin_steam_sections: player, most-played
          plugin_steam_user: ${{ secrets.STEAM_UID }}
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}

  # https://github.com/lowlighter/metrics/blob/master/source/plugins/music/README.md
  github-metrics-music:
    runs-on: ubuntu-latest
    steps:
      # - name: Spotify - Recently listed
      #   uses: lowlighter/metrics@latest
      #   with:
      #     token: NOT_NEEDED
      #     filename: metrics/spotify-recent.svg
      #     base: ""
      #     config_timezone: Asia/Shanghai
      #     plugin_music: yes
      #     plugin_music_provider: spotify
      #     plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
      #     plugin_music_mode: recent
      #     plugin_music_limit: 10
      #     plugin_music_played_at: yes # invalid config for plugin_music_mode: top
      - name: Spotify - Top tracks
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/spotify-top-tracks-short.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_mode: top
          plugin_music_time_range: short # short: 4 weeks; medium: 6 months; long: several years
          plugin_music_top_type: tracks
          plugin_music_limit: 10
      - name: Spotify - Top tracks
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/spotify-top-tracks-medium.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_mode: top
          plugin_music_time_range: medium # short: 4 weeks; medium: 6 months; long: several years
          plugin_music_top_type: tracks
          plugin_music_limit: 10
      - name: Spotify - Top tracks
        uses: lowlighter/metrics@latest
        with:
          token: NOT_NEEDED
          filename: metrics/spotify-top-tracks-long.svg
          base: ""
          config_timezone: Asia/Shanghai
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKENS }}
          plugin_music_mode: top
          plugin_music_time_range: long # short: 4 weeks; medium: 6 months; long: several years
          plugin_music_top_type: tracks
          plugin_music_limit: 10
